services:
  server:
    networks:
      aimcheck: {}
      shared-proxy:
        aliases:
          - aimcheck-server

  client:
    networks:
      aimcheck: {}
      shared-proxy:
        aliases:
          - aimcheck-client

networks:
  aimcheck: {}
  shared-proxy:
    external: true
    name: ${SHARED_PROXY_NETWORK:-shared-proxy}
